#!/bin/bash

# Laravel Install
laravel_install () {
    composer create-project --prefer-dist laravel/laravel=10.* .
    sed -i'' -e "s/\(DB_CONNECTION=\).*/\1mysql/" .env
    sed -i'' -e "s/\(DB_HOST=\).*/\1db/" .env
    sed -i'' -e "s/\(DB_PORT=\).*/\13306/" .env
    sed -i'' -e "s/\(DB_DATABASE=\).*/\1laravel/" .env
    sed -i'' -e "s/\(DB_USERNAME=\).*/\1laravel-user/" .env
    sed -i'' -e "s/\(DB_PASSWORD=\).*/\1laravel-pass/" .env
    php artisan migrate
}

# Laravel Breeze Install
laravel_breeze_install () {
    breeze_type=$1
    composer require laravel/breeze --dev
    php artisan breeze:install ${breeze_type}
    npm install
    npm run dev
}

# Laravel Jetstream Install
laravel_jetstream_install () {
    jetstream_type=$1
    options=${@:2}
    composer require laravel/jetstream
    php artisan jetstream:install ${jetstream_type} ${options}
    php artisan migrate:refresh
}

# Help
usage () {
  cat << EOM
Usage: $(basename "$0") [OPTION]...
      --breeze          install laravel-breeze
      --breeze=TYPE     install laravel-breeze TYPE: vue or react
      --jetstream       install laravel-jetstream
      --jetstream=TYPE  install laravel-jetstream TYPE: livewire or inertia
      --teams           add teams option for laravel-jetstream
      --api             add API support option for laravel-jetstream
      --verification    add email verification support option for laravel-jetstream
  -h, --help            display this help and exit
  -v, --version         output version information and exit
EOM
}

# Version
version () {
    echo 'v1.0.0'
}

cd /var/www

use_ui=false
use_breeze=false
use_jetstream=false
jetstream_options=''

while getopts :-: opt; do
    if [ "$opt" = - ]; then
        case "${OPTARG%%=*}" in
            breeze)
                use_breeze=true
                case "${OPTARG##*=}" in
                    vue|react)
                        breeze_type="${OPTARG##*=}"
                        ;;
                esac
                ;;
            jetstream)
                use_jetstream=true
                case "${OPTARG##*=}" in
                    livewire|inertia)
                        jetstream_type="${OPTARG##*=}"
                        ;;
                esac
                ;;
            teams)
                jetstream_options="${jetstream_options} --teams"
                ;;
            api)
                jetstream_options="${jetstream_options} --api"
                ;;
            verification)
                jetstream_options="${jetstream_options} --verification"
                ;;
            help)
                usage
                exit
                ;;
            version)
                version
                exit
                ;;
            *)
                echo "$0: illegal option -- ${OPTARG%%=*}"
                usage
                exit 1
                ;;
        esac
    else
        case "$opt" in
            h)
                usage
                exit
                ;;
            v)
                version
                exit
                ;;
            *)
                echo "$0: illegal option -$opt"
                usage
                exit 1
                ;;
        esac
    fi
    # Optional arguments
    if [ -z "$OPTARG" ] && [ "${!OPTIND}" != -* ]; then
        OPTIND=$((OPTIND + 1))
    fi
done

laravel_install
if "${use_breeze}"; then
    laravel_breeze_install ${breeze_type}
elif "${use_jetstream}"; then
    laravel_jetstream_install ${jetstream_type} ${jetstream_options}
fi
